// src/components/InterviewPreparation.jsx
import { jsPDF } from "jspdf";
import { 
  Sparkles, Loader2, BookOpen, Lightbulb, MessageSquare, 
  AlertCircle, RefreshCw, CheckCircle2, BrainCircuit, 
  Download
} from "lucide-react";
import { useSelector, useDispatch } from "react-redux";
import { generateInterviewPrep } from "../redux/slices/aiSlice";
import { toast } from "react-toastify";

export default function InterviewPreparation({ jobId, jobTitle }) {
  const dispatch = useDispatch();
  
  const preparation = useSelector((state) => state.ai.interviewPrep);
  const isLoading = useSelector((state) => state.ai.isPrepLoading);
  const error = useSelector((state) => state.ai.prepError);

  const generatePrep = async () => {
    try {
      await dispatch(generateInterviewPrep(jobId)).unwrap();
      toast.success("Preparation plan generated!");
    } catch (err) {
      toast.error("Failed to generate prep:");
      toast.info(`${err}`);
    }
  };

const handleDownloadPDF = () => {
    if (!preparation) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxTextWidth = pageWidth - (margin * 2);
    let currentY = 20;

    const addText = (text, fontSize = 10, isBold = false, color = [0, 0, 0]) => {
      doc.setFontSize(fontSize);
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setTextColor(...color);
      const splitText = doc.splitTextToSize(text, maxTextWidth);
      
      if (currentY + (splitText.length * 5) > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        currentY = 20;
      }
      
      doc.text(splitText, margin, currentY);
      currentY += (splitText.length * 5) + 4;
    };

    const addHeader = (title, iconChar) => {
      if (currentY > doc.internal.pageSize.getHeight() - 30) doc.addPage();
      currentY += 5;
      addText(`${iconChar} ${title}`, 14, true, [79, 70, 229]);
      currentY += 2;
    };

    doc.setFillColor(238, 242, 255);
    doc.rect(0, 0, pageWidth, 40, "F");
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229);
    doc.text("AI Interview Preparation", margin, 20);
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`For: ${jobTitle}`, margin, 30);
    currentY = 50;

    if (preparation.questions?.length > 0) {
      addHeader("Likely Interview Questions", "Q.");
      preparation.questions.forEach((q, idx) => {
        const cleanQ = q.replace(/\*\*(.*?)\*\*/g, '$1');
        addText(`${idx + 1}. ${cleanQ}`, 11, false, [30, 30, 30]);
        currentY += 2;
      });
    }

    if (preparation.topics?.length > 0) {
      addHeader("Key Topics to Revise", "T.");
      preparation.topics.forEach((topic) => {
        addText(`• ${topic.title}`, 11, true, [30, 30, 30]);
        if (topic.details) {
          topic.details.forEach((detail) => {
            const cleanDetail = detail.replace(/\*\*(.*?)\*\*/g, '$1');
            addText(`   - ${cleanDetail}`, 10, false, [80, 80, 80]);
          });
        }
      });
    }

    if (preparation.tips?.length > 0) {
      addHeader("Preparation Tips", "T.");
      preparation.tips.forEach((tip) => {
        const cleanTip = tip.replace(/\*\*(.*?)\*\*/g, '$1');
        addText(` ${cleanTip}`, 11, false, [30, 30, 30]);
        currentY += 2;
      });
    }

    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by TalentHub AI • Page ${i} of ${pageCount}`, margin, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save(`Interview-Prep-${jobTitle.replace(/\s+/g, '-')}.pdf`);
  };


  return (
    <div className="bg-white rounded-2xl border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] overflow-hidden flex flex-col">
      {/* Header */}
      <div className="p-6 border-b-4 border-black bg-linear-to-r from-cyan-300 to-purple-300">
        <div className="flex items-start gap-4">
          <div className="p-3 bg-white rounded-xl border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] shrink-0">
            <BrainCircuit className="w-6 h-6 text-black" />
          </div>
          <div className="pt-1">
            <h2 className="text-xl font-black text-black">AI Interview Prep</h2>
            <p className="text-sm text-black font-bold mt-1">
              Personalized for <span className="bg-yellow-300 px-1.5 py-0.5 rounded border-2 border-black inline-block">{jobTitle}</span>
            </p>
          </div>
        </div>
      </div>

      <div className="p-6 sm:p-8">
        {/* Initial State */}
        {!preparation && !isLoading && !error && (
          <div className="min-h-80 flex flex-col items-center justify-center text-center p-6">
            <div className="w-20 h-20 bg-purple-300 rounded-2xl flex items-center justify-center mx-auto mb-5 border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
              <Sparkles className="w-10 h-10 text-black" />
            </div>
            <h3 className="text-xl font-black text-black mb-2">Ready to ace your interview?</h3>
            <p className="text-black font-medium mb-6 max-w-sm mx-auto text-sm leading-relaxed">
              Our AI will analyze the job description and your profile to generate likely questions, key topics, and pro tips.
            </p>
            <button
              onClick={generatePrep}
              className="inline-flex items-center gap-2 px-6 py-3 bg-purple-500 text-black font-black border-2 border-black rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 transition-all"
            >
              <Sparkles className="w-5 h-5" />
              Generate Preparation
            </button>
          </div>
        )}

        {/* Loading State */}
        {isLoading && (
          <div className="min-h-80 flex flex-col items-center justify-center text-center p-6">
            <Loader2 className="w-10 h-10 animate-spin text-black mx-auto mb-4" />
            <p className="text-black font-black">AI is analyzing the job...</p>
            <p className="text-sm text-gray-700 font-medium mt-1">Crafting personalized questions and tips</p>
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="min-h-80 flex flex-col items-center justify-center text-center p-6">
            <div className="w-16 h-16 bg-red-400 rounded-full flex items-center justify-center mx-auto mb-4 border-4 border-black">
              <AlertCircle className="w-8 h-8 text-black" />
            </div>
            <h3 className="text-lg font-black text-black mb-2">Generation Failed</h3>
            <p className="text-black font-medium mb-6 max-w-sm mx-auto text-sm">{error}</p>
            <button
              onClick={generatePrep}
              className="inline-flex items-center gap-2 px-6 py-3 bg-red-400 text-black font-black border-2 border-black rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 transition-all"
            >
              <RefreshCw className="w-4 h-4" />
              Try Again
            </button>
          </div>
        )}

        {/* Success State */}
        {preparation && !error && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            
            {/* 1. Interview Questions */}
            {preparation.questions?.length > 0 && (
              <div className="p-5 bg-blue-200 border-2 border-black rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-2 bg-white rounded-lg border-2 border-black">
                    <MessageSquare className="w-4 h-4 text-black" />
                  </div>
                  <h3 className="font-black text-black uppercase tracking-wide">Likely Questions</h3>
                </div>
                <div className="space-y-3">
                  {preparation.questions.map((q, idx) => (
                    <div key={idx} className="group p-4 bg-white border-2 border-black rounded-xl shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 transition-all">
                      <div className="flex items-start gap-3">
                        <span className="shrink-0 w-7 h-7 flex items-center justify-center bg-purple-500 text-black text-xs font-black rounded-full border-2 border-black mt-0.5">
                          {idx + 1}
                        </span>
                        <p 
                          className="text-sm text-black font-medium leading-relaxed" 
                          dangerouslySetInnerHTML={{ 
                            __html: q.replace(/\*\*(.*?)\*\*/g, '<strong class="font-black text-black">$1</strong>') 
                          }} 
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 2. Key Topics to Revise */}
            {preparation.topics?.length > 0 && (
              <div>
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-2 bg-cyan-300 rounded-lg border-2 border-black">
                    <BookOpen className="w-4 h-4 text-black" />
                  </div>
                  <h3 className="font-black text-black uppercase tracking-wide">Key Topics to Revise</h3>
                </div>
                <div className="grid grid-cols-1 gap-4">
                  {preparation.topics.map((topic, idx) => (
                    <div key={idx} className="flex flex-col h-full p-5 bg-white border-2 border-black rounded-xl shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 transition-all">
                      <h4 className="font-black text-black text-sm mb-4 flex items-center gap-2 pb-3 border-b-2 border-gray-100">
                        <span className="w-2 h-2 bg-purple-500 rounded-full shrink-0 border border-black"></span>
                        {topic.title}
                      </h4>
                      <ul className="space-y-3 mt-auto">
                        {topic.details?.map((detail, dIdx) => (
                          <li key={dIdx} className="flex items-start gap-3 text-xs text-black font-medium leading-relaxed">
                            <CheckCircle2 className="w-4 h-4 text-green-600 shrink-0 mt-0.5" />
                            <span 
                              dangerouslySetInnerHTML={{ 
                                __html: detail.replace(/\*\*(.*?)\*\*/g, '<strong class="font-black text-black">$1</strong>') 
                              }} 
                            />
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 3. Preparation Tips */}
            {preparation.tips?.length > 0 && (
              <div className="p-5 bg-yellow-200 rounded-2xl border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-2 bg-white rounded-lg border-2 border-black">
                    <Lightbulb className="w-4 h-4 text-black" />
                  </div>
                  <h3 className="font-black text-black uppercase tracking-wide">Pro Preparation Tips</h3>
                </div>
                <ul className="space-y-3">
                  {preparation.tips.map((tip, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-sm text-black font-medium leading-relaxed">
                      <span className="text-black mt-1 shrink-0 font-black">✦</span>
                      <span 
                        dangerouslySetInnerHTML={{ 
                          __html: tip.replace(/\*\*(.*?)\*\*/g, '<strong class="font-black text-black">$1</strong>') 
                        }} 
                      />
                    </li>
                  ))}
                </ul>
              </div>
            )}
            
            {/* Action Buttons Footer */}
            <div className="mt-10 pt-8 border-t-4 border-black flex flex-col gap-4">
              <button
                onClick={handleDownloadPDF}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-black text-white font-black border-2 border-black rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 transition-all"
              >
                <Download className="w-4 h-4" />
                Download as PDF
              </button>
              
              <button
                onClick={generatePrep}
                disabled={isLoading}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-white text-black font-black border-2 border-black rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-0.5 disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none disabled:translate-y-0 transition-all"
              >
                <RefreshCw className={`w-4 h-4 ${isLoading ? "animate-spin" : ""}`} />
                Regenerate Preparation
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}